### ISSUE TITLE
Select text color

### ISSUE THREAD

**Issue by ghost** [MiguelCastillo/Brackets-Themes#108]
I noticed, in one of your updates, when you select text, the selected text's background is so light, that you can hardly see it.

**Comment by MiguelCastillo** [comment]
Slow on this one. Here is a screenshot of the new color.  What do you think?
![screen shot 2015-01-20 at 12 03 21 pm](https://cloud.githubusercontent.com/assets/1457701/5821755/78625ee4-a09c-11e4-806f-afe64ecf63f5.png)

**Comment by MiguelCastillo** [comment]
Fixed with https://github.com/MiguelCastillo/Brackets-Themes/commit/83c989f1c135915e4bbf7d056bc082e0e1719084
