### ISSUE TITLE
Delkos Incredible!

### ISSUE THREAD

**Issue by ghost** [MiguelCastillo/Brackets-Themes#109]
Delkos
======
When I went into my `package.json` file, I put my cursor next to a curly brace, ___it lit up pink and cyan with a transition___. Do you think you can do that with HTML, XML, tags?

![screen shot 2014-12-17 at 11 25 25 am](https://cloud.githubusercontent.com/assets/8144127/5477359/7af439de-85df-11e4-9d57-532a7e89c727.png)

**Comment by MiguelCastillo** [comment]
Fixed.
