### ISSUE TITLE
Theme custom styles get overridden

### ISSUE THREAD

**Issue by sirnornur** [MiguelCastillo/Brackets-Themes#110]
![untitled](https://cloud.githubusercontent.com/assets/10341893/5571212/e111bf00-8faf-11e4-9ce9-a7254166a2a9.png)
After latest update my .CodeMirror-selected, .CodeMirror-matchingbracket,
.CodeMirror-matchingtag styles are forcedly overridden. This is very frustrating, especially after getting used to a favorite theme.
I think this is related to "Auto detection of dark themes so that Brackets can do its dark theme specific styling." feature.
How can I use my custom styles for .CodeMirror-selected, .CodeMirror-matchingbracket,
.CodeMirror-matchingtag ?

**Comment by MiguelCastillo** [comment]
@sirnornur Sorry for the slow response.  I removed the `!important;` flag in resets.css that was causing the problem...  https://github.com/MiguelCastillo/Brackets-Themes/commit/83c989f1c135915e4bbf7d056bc082e0e1719084

The changes are in master.  Do you think you can give this a quick test to confirm this fixes the problem for you?

**Comment by MiguelCastillo** [comment]
@sirnornur All the tests I ran reflect that this issue is fixed.  I am closing it...  Please feel free to open new issues up if anything else comes up :)
