### ISSUE TITLE
Peacock problem

### ISSUE THREAD

**Issue by DrPandemic** [MiguelCastillo/Brackets-Themes#111]
I'm using Brackets on Linux. The .CodeMirror-gutter-elt padding cause me a problem where I loose the first characters of every line. By removing the padding, it solves the problem.
![1](https://cloud.githubusercontent.com/assets/3250155/6543888/13e6286a-c4ff-11e4-8faf-529a7efdcfe4.png)
![2](https://cloud.githubusercontent.com/assets/3250155/6543889/15a14dd8-c4ff-11e4-8149-bfd25ef744fc.png)
Should I do a PR in this repo to change a theme?
Thank you for your time

**Comment by MiguelCastillo** [comment]
@DrPandemic Hi, yes please you can submit a PR right here

**Comment by MiguelCastillo** [comment]
thanks!!
