### ISSUE TITLE
Themes Do Not change the appearance as expected (Ubuntu)

### ISSUE THREAD

**Issue by mojo706** [MiguelCastillo/Brackets-Themes#23]
Hello,
I have been having this issue since Sprint 29 on Ubuntu 12.04. The themes work great on Windows but are distorted on Ubuntu. The colors are dim very dim. Sometimes I cannot tell whether I have highlighted anything. See the screenshot below. Thats the ambiance theme (my favourite) but it doesn't look as it does on Windows.
![themeambiance](https://f.cloud.github.com/assets/908380/1094930/9446928c-16d8-11e3-9a4a-f7c98a449f7a.png)

**Comment by xuton00** [comment]
can anyone plz tell me that ,,,how i intall theme in ubuntu for brackets ??? 
i tried many time but can't find appropriate answer for this problem.... 
:( :-1:
